package constants

var (
	Constants_12                                                 = "*"
	Fmt                                                          = "fmt"
	Googlegolangorgapicalendarv                                  = "google.golang.org/api/calendar/v3"
	Testing                                                      = "testing"
	Constants_11                                                 = "."
	Strings                                                      = "strings"
	Constants_2                                                  = ""
	Analysisconfigerrs                                           = "analysis config err: %s"
	Initprovidererrors                                           = "init provider error: %s"
	Constants_9                                                  = ""
	Snosuchfileordir                                             = "%s: no such file or dir"
	Hostuserpostgrespasswordpassportdbnamepostgressslmodedisable = "host=127.0.0.1 user=postgres password=pass port=5432 dbname=postgres sslmode=disable"
	Googlegolangorgapidrivev                                     = "google.golang.org/api/drive/v3"
	Constants_1                                                  = ""
	Constants_6                                                  = ""
	Constants_7                                                  = ""
	Context                                                      = "context"
	Constants_8                                                  = ""
	Constants_10                                                 = ""
	NA                                                           = "N/A"
	Googlegolangorgapioption                                     = "google.golang.org/api/option"
	Googlegolangorgapipeoplev                                    = "google.golang.org/api/people/v1"
	Constants_0                                                  = ""
	Newclientserrs                                               = "new clients err: %s"
	Contextcanceled                                              = "context canceled"
	Constants_3                                                  = ""
	Impersonateduseremailmustbeconfigured                        = "impersonated_user_email must be configured"
	Providerpulltableerrors                                      = "provider pull table error: %s"
	Golangorgxoauth                                              = "golang.org/x/oauth2"
	Golangorgxoauthgoogle                                        = "golang.org/x/oauth2/google"
	Constants_5                                                  = ""
	Googleworkspace                                              = "googleworkspace"
	V                                                            = "v0.0.1"
	Accountinformationnotfound                                   = "account information not found"
	Notsupported                                                 = "not_supported"
	SELEFRADATABASEDSN                                           = "SELEFRA_DATABASE_DSN"
	Errors                                                       = "errors"
	Os                                                           = "os"
	Googlegolangorgapigmailv                                     = "google.golang.org/api/gmail/v1"
	Constants_4                                                  = ""
)
